kind: pipeline
name: build

steps:
  - name: backend
    image: golang
    commands:
      - echo "OK"

---
kind: pipeline
name: notify
depends_on:
  - build

steps:
  - name: notify
    image: golang
    commands:
      - echo "hello"

trigger:
  status:
    - success
    - failure
